name: device_tracking_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  flutter_udid: ^4.0.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
