// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdX9Qnx0YaK7XdjTjjC0a3865y008EvI',
    appId: '1:916817013006:android:b0f1eff6c46fdeea9d8f5f',
    messagingSenderId: '916817013006',
    projectId: 'device-tracking-f8705',
    storageBucket: 'device-tracking-f8705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsECcHLaMejICBsUg2UVqObDm2eMjzEj8',
    appId: '1:916817013006:ios:20f6546655883b619d8f5f',
    messagingSenderId: '916817013006',
    projectId: 'device-tracking-f8705',
    storageBucket: 'device-tracking-f8705.firebasestorage.app',
    androidClientId: '916817013006-an6ng4ust1au207nae6ad0e6mr3uv97l.apps.googleusercontent.com',
    iosClientId: '916817013006-44475dscri2nhc1vf7r1elkmhe091sq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.deviceTrackingFlutterApp',
  );

}