name: Android Release Build & Upload

on:
  push:
    branches:
      - main # change this to qa-builds if you want to test on a QA branch

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"

      # Cache pub dependencies for faster builds
      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}

      # Install project dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build release APK
      - name: Build Android release APK
        run: flutter build apk --release

      # Install Firebase CLI (via npm for faster caching)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Verify Firebase CLI installed
      - name: Check Firebase CLI version
        run: firebase --version

      # Upload APK to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups testers \
            --release-notes "Automated build from QA branch" \
            --token ${{ secrets.FIREBASE_CLI_TOKEN }}

        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
